### PR TITLE
Some minor bug fix and enhancement

### PR DESCRIPTION
**Pull request by ZwodahS**
Fix a bug when switching window.
Add options to automatically clear the highlight on certain events.

### CODE REVIEW

**Comment by EugenHotaj** [comment]
@lygaret could we please pull this is in? This is exactly the bugs I ran into and was hoping to fix!

**Comment by ZwodahS** [comment]
you can just install from my repo instead

**Comment by lygaret** [comment]
@EugenHotaj sorry I hadn't seen this! 

I don't use this anymore, I should explicitly mark it abandoned. 
@ZwodahS you have a repo, would you like me to point at your fork in the readme?

**Comment by ZwodahS** [comment]
Sure, you can link to me

**Pull request merged**
